services:
- type: web
  name: issuing-treasury
  env: node
  plan: free
  buildCommand: npm install; npx prisma db push; npm run build;
  startCommand: NEXTAUTH_URL=$RENDER_EXTERNAL_URL CONNECT_ONBOARDING_REDIRECT_URL=$RENDER_EXTERNAL_URL npm run start
  autoDeploy: false
  envVars:
    - key: PORT
      value: 10000
    - key: DATABASE_URL
      fromDatabase:
        name: issuing-treasury-db
        property: connectionString
    - key: STRIPE_SECRET_KEY
      sync: false
    - key: NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY
      sync: false
    - key: NEXTAUTH_SECRET
      generateValue: true

databases:
- name: issuing-treasury-db
  plan: free
  databaseName: issuing_treasury
  user: issuing_treasury
  ipAllowList: [] # only allow internal connections
